### ISSUE TITLE
Hard link instead of task scheduler

### ISSUE THREAD

**Issue by mobydi** [gornostal/Chrome-Bookmarks-Online#1]
# You can make hard link to "Bookmarks" file instead of using task scheduler.

_samlpe:_ Windows Vista\7

```
mklink /H "C:\Users\<Username>\Dropbox\Public\bookmarks\Bookmarks" "C:\Users\<Username>\AppData\Local\Google\Chrome\User Data\Default\Bookmarks"  
```

**Comment by gornostal** [comment]
I know that hard (or sym) links is not working on Linux.
I guess it happens because link doesn't change modification time and therefore Dropbox doesn't sync file properly.

Are sure you don't have the same issue on Windows making hard links?

Besides, AFAIK you can only make hard links within one partition. 
Have you tried same trick with symlinks?
